base_url = "https://zola-shimong.netlify.com"
title = "子雲"
compile_sass = true
generate_feed = true

taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[extra]
author = "Ziyun Li"
shimong_menu = [
    {url = "$BASE_URL/posts", name = "blog"},
    {url = "$BASE_URL/about", name = "about"},
    {url = "$BASE_URL/categories", name = "categories"},
    {url = "$BASE_URL/tags", name = "tags"},
]
