base_url = "https://zola-shimong.netlify.com"
title = "Hello"
compile_sass = true
generate_feed = true

# taxonomies = [
#     {name = "categories", feed = true},
#     {name = "tags", feed = true},
# ]

[extra]
author = "Vincent"
shimong_menu = [
    {url = "$BASE_URL/posts", name = "blog"},
    {url = "$BASE_URL/about", name = "about"},
    {url = "https://github.com/ziyunli", name = "github"},
    {url = "https://twitter.com/ziyun_li", name = "twitter"},
]
